Repository Team-Motivoo/Motivoo-Server, pull requests merged in 2024-01, with the labels that each got.

#5 [REFACTOR] Exception 및 응답 형식 피드백 사항 반영
  src/main/java/sopt/org/motivooServer/domain/HealthCheck.java
  src/main/java/sopt/org/motivooServer/domain/mission/exception/MissionException.java
  src/main/java/sopt/org/motivooServer/domain/mission/exception/MissionExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserException.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserExceptionType.java
  src/main/java/sopt/org/motivooServer/global/advice/BusinessException.java
  src/main/java/sopt/org/motivooServer/global/advice/BusinessExceptionType.java
  src/main/java/sopt/org/motivooServer/global/advice/ErrorResponse.java
  src/main/java/sopt/org/motivooServer/global/advice/ErrorType.java
  src/main/java/sopt/org/motivooServer/global/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/common/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/common/response/ApiResponse.java
  src/main/java/sopt/org/motivooServer/global/response/ApiResponse.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🪄API, 🐈예준🐈

#3 [CHORE] 프로젝트 초기 세팅
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .gitignore
  Dockerfile
  build.gradle
  src/main/java/sopt/org/motivooServer/domain/HealthCheck.java
  src/main/java/sopt/org/motivooServer/domain/mission/exception/MissionException.java
  src/main/java/sopt/org/motivooServer/domain/mission/exception/MissionExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserException.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserExceptionType.java
  src/main/java/sopt/org/motivooServer/global/advice/BusinessException.java
  src/main/java/sopt/org/motivooServer/global/advice/BusinessExceptionType.java
  src/main/java/sopt/org/motivooServer/global/advice/ErrorResponse.java
  src/main/java/sopt/org/motivooServer/global/advice/ErrorType.java
  src/main/java/sopt/org/motivooServer/global/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/config/JpaAuditingConfig.java
  src/main/java/sopt/org/motivooServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/motivooServer/global/response/ApiResponse.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/resources/application-dev.yml
  src/main/resources/application.properties
Labels: 🔥PULL REQUEST, ☁️DATABASE, 🧹CHORE, 🐈예준🐈

#11 [DOCS] README.md 추가
  README.md
Labels: 📃DOCS, 🔥PULL REQUEST, 🐈예준🐈

#9 [FEAT] 슬랙 알림, Swagger+Restdocs API 문서 자동화 연동
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .gitignore
  build.gradle
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/global/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/config/swagger/SwaggerConfig.java
  src/main/java/sopt/org/motivooServer/global/healthcheck/HealthCheckApi.java
  src/main/java/sopt/org/motivooServer/global/healthcheck/HealthCheckController.java
  src/main/java/sopt/org/motivooServer/global/healthcheck/SlackTestController.java
  src/main/java/sopt/org/motivooServer/global/response/ApiResponse.java
  src/main/java/sopt/org/motivooServer/global/util/slack/SlackUtil.java
  src/main/resources/application-dev.yml
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/sopt/org/motivooServer/MotivooServerApplicationTests.java
  src/test/java/sopt/org/motivooServer/controller/BaseControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/HealthCheckControllerTest.java
  src/test/resources/application.yml
Labels: 🔥PULL REQUEST, 🧹CHORE, 🪄API, 🐈예준🐈

#13 [FEAT] AWS S3를 이용한 이미지 업로드 구현
  .github/workflows/CD.yml
  build.gradle
  docker-compose.yml
  scripts/deploy.sh
  src/main/java/sopt/org/motivooServer/global/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/config/aws/AWSConfig.java
  src/main/java/sopt/org/motivooServer/global/healthcheck/HealthCheckController.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/java/sopt/org/motivooServer/global/util/s3/PreSignedUrlResponse.java
  src/main/java/sopt/org/motivooServer/global/util/s3/S3BucketDirectory.java
  src/main/java/sopt/org/motivooServer/global/util/s3/S3ExceptionType.java
  src/main/java/sopt/org/motivooServer/global/util/s3/S3Service.java
  src/main/resources/application-dev.yml
Labels: 🔥PULL REQUEST, ☄️DEPLOY, 🪄API, 🐈예준🐈

#22 [FIX] 테스트 실패로 인한 빌드 실패 해결
  README.md
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/sopt/org/motivooServer/MotivooServerApplicationTests.java
  src/test/java/sopt/org/motivooServer/controller/BaseControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/HealthCheckControllerTest.java
Labels: 🐞 BUGFIX, 🔥PULL REQUEST, 🐈예준🐈

#20 [REFACTOR] 카카오 로그인 피드백 반영
  build.gradle
  http/motivoo.http
  src/main/java/sopt/org/motivooServer/MotivooServerApplication.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/CustomAccessDeniedHandler.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/CustomJwtAuthenticationEntryPoint.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtAuthenticationFilter.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtTokenProvider.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtValidationType.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/OAuth2ClientRegistrationRepositoryConfig.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/RedisConfig.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/UserAuthentication.java
  src/main/java/sopt/org/motivooServer/domain/auth/controller/OauthController.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/redis/RefreshToken.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/request/OauthTokenRequest.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/request/RefreshRequest.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/LoginResponse.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/OauthTokenResponse.java
  src/main/java/sopt/org/motivooServer/domain/auth/repository/TokenRedisRepository.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/OAuth2UserInfo.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/OauthService.java
  src/main/java/sopt/org/motivooServer/domain/user/dto/request/KakaoUserProfile.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/SocialPlatform.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/UserType.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/global/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/resources/application-dev.yml
  src/test/java/sopt/org/motivooServer/MotivooServerApplicationTests.java
  src/test/java/sopt/org/motivooServer/controller/BaseControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/HealthCheckControllerTest.java
Labels: 🔨REFACTOR, 🐰혜연🐰

#26 [FEAT] 테스트 Redis 설정파일 에러 해결
  .gitignore
  build.gradle
  src/main/java/sopt/org/motivooServer/domain/auth/config/RedisConfig.java
  src/main/java/sopt/org/motivooServer/domain/auth/repository/TokenRedisRepository.java
  src/main/resources/application-dev.yml
  src/test/java/sopt/org/motivooServer/MotivooServerApplicationTests.java
  src/test/java/sopt/org/motivooServer/controller/BaseControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/HealthCheckControllerTest.java
  src/test/java/sopt/org/motivooServer/util/ApiDocumentUtil.java
  src/test/resources/application.yml
Labels: 🚨HOTFIX, 🔥PULL REQUEST, 🐈예준🐈

#27 [HOTFIX] Security 필터 로직 수정
  build.gradle
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtAuthenticationFilter.java
Labels: 🚨HOTFIX, 🧹MODIFY, 🐈예준🐈

#29 [FEAT] 마이페이지 API 구현
  .gitignore
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtTokenProvider.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/Health.java
  src/main/java/sopt/org/motivooServer/domain/health/exception/HealthExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/health/repository/HealthRepository.java
  src/main/java/sopt/org/motivooServer/domain/user/controller/UserController.java
  src/main/java/sopt/org/motivooServer/domain/user/dto/response/MyHealthInfoResponse.java
  src/main/java/sopt/org/motivooServer/domain/user/dto/response/MyPageInfoResponse.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/user/service/UserService.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/test/java/sopt/org/motivooServer/controller/HealthCheckControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/UserControllerTest.java
Labels: 🔥PULL REQUEST, 🪄API, 🐈예준🐈

#30 [FEAT] 운동 정보 입력 API
  src/main/java/sopt/org/motivooServer/MotivooServerApplication.java
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtTokenProvider.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/OauthService.java
  src/main/java/sopt/org/motivooServer/domain/health/dto/request/OnboardingRequest.java
  src/main/java/sopt/org/motivooServer/domain/health/dto/response/OnboardingResponse.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseFrequency.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseLevel.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseTime.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseType.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/Health.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/HealthNote.java
  src/main/java/sopt/org/motivooServer/domain/health/exception/HealthExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/health/repository/HealthRepository.java
  src/main/java/sopt/org/motivooServer/domain/health/service/CalculateScore.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/controller/ParentChildController.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/entity/Parentchild.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentChildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentChildService.java
  src/main/java/sopt/org/motivooServer/domain/user/controller/UserController.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/UserType.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/test/java/sopt/org/motivooServer/MotivooServerApplicationTests.java
Labels: 🔥PULL REQUEST, 🪄API, 🐰혜연🐰

#33 [FEAT] 초대코드 입력 (매칭) API
  src/main/java/sopt/org/motivooServer/domain/auth/dto/request/OauthTokenRequest.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/controller/ParentChildController.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/dto/request/InviteRequest.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/dto/response/InviteResponse.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/entity/Parentchild.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/exception/ParentchildExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentChildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentChildService.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
Labels: 🔥PULL REQUEST, 🪄API, ✨FEAT, 🐰혜연🐰

#38 [FEAT] 오늘의 미션에 관한 API 구현
  build.gradle
  src/main/java/sopt/org/motivooServer/domain/health/dto/request/OnboardingRequest.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseFrequency.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseLevel.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseTime.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseType.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/HealthNote.java
  src/main/java/sopt/org/motivooServer/domain/mission/controller/HomeController.java
  src/main/java/sopt/org/motivooServer/domain/mission/controller/UserMissionController.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/request/MissionStepStatusRequest.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/request/TodayMissionChoiceRequest.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/MissionHistoryResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/MissionStepStatusResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/ParentchildMissionDto.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/TodayMissionResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/TodayUserMissionDto.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/CompletedStatus.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/Mission.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/MissionQuest.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/MissionType.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMissionChoices.java
  src/main/java/sopt/org/motivooServer/domain/mission/exception/MissionExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/mission/repository/MissionQuestRepository.java
  src/main/java/sopt/org/motivooServer/domain/mission/repository/MissionRepository.java
  src/main/java/sopt/org/motivooServer/domain/mission/repository/UserMissionChoicesRepository.java
  src/main/java/sopt/org/motivooServer/domain/mission/repository/UserMissionRepository.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionScheduler.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/exception/ParentchildExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentChildService.java
  src/main/java/sopt/org/motivooServer/domain/step/exception/StepException.java
  src/main/java/sopt/org/motivooServer/domain/step/exception/StepExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/user/dto/response/MyHealthInfoResponse.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/UserType.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/global/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/config/ScheduleConfig.java
  src/main/java/sopt/org/motivooServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/java/sopt/org/motivooServer/global/util/s3/S3Service.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/sopt/org/motivooServer/controller/UserMissionControllerTest.java
  src/test/java/sopt/org/motivooServer/util/DateCompareTest.java
Labels: 🔥PULL REQUEST, ☁️DATABASE, 🪄API, ✨FEAT, 🐈예준🐈

#42 [DOCS] README.md 수정
  README.md
  src/main/java/sopt/org/motivooServer/domain/health/entity/Health.java
  src/main/java/sopt/org/motivooServer/domain/health/exception/HealthExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionScheduler.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/entity/Parentchild.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentChildService.java
  src/main/java/sopt/org/motivooServer/domain/user/dto/response/MyHealthInfoResponse.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserExceptionType.java
  src/main/java/sopt/org/motivooServer/global/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/external/s3/PreSignedUrlResponse.java
  src/main/java/sopt/org/motivooServer/global/external/s3/S3BucketDirectory.java
  src/main/java/sopt/org/motivooServer/global/external/s3/S3ExceptionType.java
  src/main/java/sopt/org/motivooServer/global/external/s3/S3Service.java
  src/main/java/sopt/org/motivooServer/global/external/s3/config/AWSConfig.java
  src/main/java/sopt/org/motivooServer/global/external/slack/SlackService.java
  src/main/java/sopt/org/motivooServer/global/healthcheck/HealthCheckController.java
  src/test/java/sopt/org/motivooServer/controller/BaseControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/HomeControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/UserMissionControllerTest.java
Labels: 📃DOCS, 🔥PULL REQUEST, 🐈예준🐈

#48 [FEAT] 오늘의 미션 관련 API 컨트롤러 테스트 추가
  .gitignore
  build.gradle
  src/main/java/sopt/org/motivooServer/domain/common/BaseTimeEntity.java
  src/main/java/sopt/org/motivooServer/domain/mission/controller/UserMissionController.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/MissionHistoryResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/TodayUserMissionDto.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/Mission.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/MissionQuest.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/global/config/swagger/SwaggerConfig.java
  src/main/java/sopt/org/motivooServer/global/healthcheck/SlackTestController.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/sopt/org/motivooServer/controller/HealthCheckControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/HomeControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/UserControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/UserMissionControllerTest.java
  src/test/java/sopt/org/motivooServer/fixture/MissionFixture.java
  src/test/java/sopt/org/motivooServer/fixture/UserFixture.java
  src/test/java/sopt/org/motivooServer/fixture/UserMissionFixture.java
Labels: 🔥PULL REQUEST, 🪄API, 🧹MODIFY, 🐈예준🐈

#49 [CHORE] openapi3 플로우 수정
  build.gradle
Labels: 🔥PULL REQUEST, ☄️DEPLOY, 🐈예준🐈

#43 [FEAT] 회원 탈퇴 API
  src/main/java/sopt/org/motivooServer/domain/auth/controller/OauthController.java
  src/main/java/sopt/org/motivooServer/domain/health/dto/response/OnboardingResponse.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseFrequency.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/Health.java
  src/main/java/sopt/org/motivooServer/domain/health/exception/HealthExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/health/repository/HealthRepository.java
  src/main/java/sopt/org/motivooServer/domain/health/service/CalculateScore.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMissionChoices.java
  src/main/java/sopt/org/motivooServer/domain/mission/repository/UserMissionChoicesRepository.java
  src/main/java/sopt/org/motivooServer/domain/mission/repository/UserMissionRepository.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/controller/ParentChildController.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/motivooServer/domain/user/controller/UserController.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/domain/user/service/ExpiredMemberDeleteBatch.java
  src/main/java/sopt/org/motivooServer/domain/user/service/UserService.java
  src/main/java/sopt/org/motivooServer/global/config/ScheduleConfig.java
  src/main/java/sopt/org/motivooServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: 🔥PULL REQUEST, 🪄API, ✨FEAT, 🐰혜연🐰

#46 [FEAT] 온보딩 정보 입력 확인 API
  src/main/java/sopt/org/motivooServer/domain/health/dto/request/OnboardingRequest.java
  src/main/java/sopt/org/motivooServer/domain/health/dto/response/CheckOnboardingResponse.java
  src/main/java/sopt/org/motivooServer/domain/health/exception/HealthExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/health/service/CalculateScore.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/controller/ParentChildController.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: 🔥PULL REQUEST, 🪄API, 🐰혜연🐰

#47 [REFACTOR] 내가 발급한 코드인지 판별하는 필드 추가
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtAuthenticationFilter.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/dto/response/InviteResponse.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/entity/Parentchild.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🐰혜연🐰

#51 [REFACTOR] parentchild 자동 생성 예외처리+온보딩 enum 클래스 필드명 변경
  build.gradle
  src/main/java/sopt/org/motivooServer/domain/auth/controller/apple/AppleApiClient.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/apple/ApplePublicKey.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/apple/ApplePublicKeys.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/apple/AppleClaimsValidator.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/apple/AppleJwtParser.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/apple/EncryptUtils.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/apple/PublicKeyGenerator.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseFrequency.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseTime.java
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseType.java
  src/main/java/sopt/org/motivooServer/domain/health/service/CalculateScore.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/user/service/ExpiredMemberDeleteBatch.java
  src/main/java/sopt/org/motivooServer/domain/user/service/UserService.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/resources/static/docs/open-api-3.0.1.json
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🐰혜연🐰

#52 [FIX] 홈 화면 미션 현황 조회 API 개선
  src/main/java/sopt/org/motivooServer/domain/mission/controller/MissionController.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/MissionStepStatusResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/Mission.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/MissionService.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/user/exception/UserExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/sopt/org/motivooServer/controller/HomeControllerTest.java
Labels: 🐞 BUGFIX, 🔥PULL REQUEST, 🪄API, 🧹MODIFY, 🐈예준🐈

#54 [FIX] 홈 화면 조회 API 버그 해결
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/MissionStepStatusResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/TodayMissionResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/test/java/sopt/org/motivooServer/controller/HomeControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/UserMissionControllerTest.java
Labels: 🚨HOTFIX, 🐞 BUGFIX, 🔥PULL REQUEST, 🧹MODIFY, 🐈예준🐈

#56 [REFACTOR] 오늘의 미션 API 로직 개선
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/MissionHistoryResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/ParentchildMissionDto.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/mission/exception/MissionExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionScheduler.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🪄API, 🧹MODIFY, 🐈예준🐈

#60 [FIX] 반환값 추가/테스트 컨트롤러 작성
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/apple/ApplePublicKey.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/OauthService.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/apple/AppleLoginService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/controller/ParentChildController.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/dto/response/InviteResponse.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/sopt/org/motivooServer/controller/ParentchildControllerTest.java
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🐰혜연🐰

#62 [FEAT] 파이어베이스 실시간 DB 연동을 통한 걸음 수 조회 및 쓰기
  .gitignore
  README.md
  build.gradle
  src/main/java/sopt/org/motivooServer/domain/mission/controller/HomeController.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/request/MissionStepStatusRequest.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/MissionType.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/global/advice/CommonExceptionType.java
  src/main/java/sopt/org/motivooServer/global/advice/ErrorType.java
  src/main/java/sopt/org/motivooServer/global/advice/GlobalExceptionHandler.java
  src/main/java/sopt/org/motivooServer/global/config/SecurityConfig.java
  src/main/java/sopt/org/motivooServer/global/external/firebase/FirebaseConfig.java
  src/main/java/sopt/org/motivooServer/global/external/firebase/FirebaseService.java
  src/main/java/sopt/org/motivooServer/global/external/firebase/UserStepScheduler.java
  src/main/java/sopt/org/motivooServer/global/response/ApiResponse.java
  src/test/java/sopt/org/motivooServer/controller/HomeControllerTest.java
Labels: 🔨REFACTOR, 🐞 BUGFIX, 🔥PULL REQUEST, ✨FEAT, 🐈예준🐈

#63 [REFACTOR] 회원탈퇴 request body 삭제
  src/main/java/sopt/org/motivooServer/domain/auth/controller/OauthController.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/OauthTokenResponse.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/OauthService.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/domain/user/service/UserService.java
  src/test/java/sopt/org/motivooServer/controller/OauthControllerTest.java
  src/test/java/sopt/org/motivooServer/controller/ParentchildControllerTest.java
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🐰혜연🐰

#64 [FIX] 충돌 해결
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/sopt/org/motivooServer/controller/ParentchildControllerTest.java
Labels: 🐞 BUGFIX, 🔥PULL REQUEST, 🐰혜연🐰

#67 [REFACTOR] 매칭시 부모-부모이거나 자식-자식인 경우 예외 처리
  src/main/java/sopt/org/motivooServer/domain/auth/controller/OauthController.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/exception/ParentchildExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/test/java/sopt/org/motivooServer/controller/OauthControllerTest.java
Labels: 🔨REFACTOR, 🐰혜연🐰

#69 [FIX] 파이어베이스 DB와의 지연 해결
  src/main/java/sopt/org/motivooServer/domain/mission/controller/HomeController.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/request/MissionStepStatusRequest.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/test/java/sopt/org/motivooServer/controller/HomeControllerTest.java
Labels: 🚨HOTFIX, 🔥PULL REQUEST, 🪄API, 🧹MODIFY, 🐈예준🐈

#70 [REFACTOR] 운동횟수 enum 필드명 변경
  src/main/java/sopt/org/motivooServer/domain/health/entity/ExerciseFrequency.java
Labels: 🔨REFACTOR, 🐰혜연🐰

#74 [FIX] 회원탈퇴 후 바로 회원가입 가능하게 리팩토링
  src/main/java/sopt/org/motivooServer/domain/auth/service/OauthService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/domain/user/service/UserService.java
Labels: 🔨REFACTOR, 🐞 BUGFIX, 🔥PULL REQUEST, 🐰혜연🐰

#76 [FIX] 오늘의 미션, 미션 히스토리 API 버그 해결
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/MissionHistoryResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/exception/MissionExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/test/java/sopt/org/motivooServer/controller/OauthControllerTest.java
Labels: 🚨HOTFIX, 🐞 BUGFIX, 🔥PULL REQUEST, 🪄API, 🧹MODIFY, 🐈예준🐈

#77 [FIX] 홈 화면 미션 달성현황 조회 API 응답 필드 추가
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/MissionStepStatusResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/global/external/s3/S3Service.java
Labels: 🐞 BUGFIX, 🔥PULL REQUEST, 🪄API, 🐈예준🐈

#79 [FIX] 미션 히스토리와의 충돌 오류 해결
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
Labels: 🚨HOTFIX, 🐞 BUGFIX, 🔥PULL REQUEST, 🪄API, 🐈예준🐈

#81 [REFACTOR] 도메인 로직으로 수정
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🐈예준🐈

#82 [REFACTOR] 유효성 검사 메서드 추가 호출
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🪄API, 🐈예준🐈

#85 [FIX] 초대코드 입력, Empty UserMission 관련 버그 해결
  src/main/java/sopt/org/motivooServer/domain/mission/exception/MissionExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/exception/ParentchildExceptionType.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
Labels: 🚨HOTFIX, 🐞 BUGFIX, 🔥PULL REQUEST, 🪄API, 🐈예준🐈

#89 [FIX] 오늘의 미션 인증 완료 시점 변경
  scripts/deploy.sh
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionScheduler.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
Labels: 🐞 BUGFIX, 🔥PULL REQUEST, 🪄API, ✨FEAT, 🧹MODIFY, 🐈예준🐈

#92 [REFACTOR] S3 버킷에 업로드한 이미지 조회 로직 개선
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/global/advice/BusinessException.java
  src/main/java/sopt/org/motivooServer/global/advice/CommonExceptionType.java
  src/main/java/sopt/org/motivooServer/global/external/s3/S3Service.java
Labels: 🔨REFACTOR, 🔥PULL REQUEST, 🪄API, 🐈예준🐈

#94 [DOCS] README.md 수정사항 반영
  README.md
Labels: 📃DOCS, 🔥PULL REQUEST, 🐈예준🐈

#96 [REFACTOR] 로그아웃, 토큰 재발급 API 문서화
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtAuthenticationFilter.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/OauthTokenResponse.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/resources/static/docs/open-api-3.0.1.json
  src/test/java/sopt/org/motivooServer/controller/OauthControllerTest.java
Labels: 📃DOCS, 🔥PULL REQUEST, 🐈예준🐈, 🐰혜연🐰

#95 [FIX] 컨트롤러 테스트 추가
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/OauthTokenResponse.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/repository/ParentchildRepository.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/test/java/sopt/org/motivooServer/controller/OauthControllerTest.java
Labels: 🐞 BUGFIX, 🐰혜연🐰

#99 [FEAT] 미션 기본 아이콘 설정
  src/main/java/sopt/org/motivooServer/domain/mission/controller/MissionController.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/Mission.java
  src/main/java/sopt/org/motivooServer/domain/mission/repository/MissionRepository.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/MissionService.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
Labels: 🔥PULL REQUEST, 🪄API, 🐰혜연🐰

#101 [CHORE] build.gradle에서 변수로 관리하도록 수정
  .github/workflows/CD.yml
  .github/workflows/CI.yml
  .gitignore
  build.gradle
Labels: 🔥PULL REQUEST, 🧹CHORE, 🐈예준🐈

#104 [FIX] 로그인 후 에러 해결
  src/main/java/sopt/org/motivooServer/domain/auth/service/OauthService.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/domain/user/service/ExpiredMemberDeleteBatch.java
  src/main/java/sopt/org/motivooServer/domain/user/service/UserService.java
Labels: 🐞 BUGFIX, 🐰혜연🐰

#106 [FIX] 회원 탈퇴 에러 해결
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtTokenProvider.java
  src/main/java/sopt/org/motivooServer/domain/auth/controller/OauthController.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/OauthService.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/controller/ParentChildController.java
  src/main/java/sopt/org/motivooServer/domain/parentchild/service/ParentchildService.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/domain/user/service/UserService.java
Labels: 🐞 BUGFIX, 🐰혜연🐰

#107 [FEAT] 데모데이 시나리오용 API 구현
  scripts/deploy.sh
  src/main/java/sopt/org/motivooServer/domain/auth/config/JwtTokenProvider.java
  src/main/java/sopt/org/motivooServer/domain/auth/dto/response/LoginResponse.java
  src/main/java/sopt/org/motivooServer/domain/auth/service/OauthService.java
  src/main/java/sopt/org/motivooServer/domain/mission/entity/UserMission.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/domain/user/entity/User.java
  src/main/java/sopt/org/motivooServer/domain/user/repository/UserRepository.java
  src/main/java/sopt/org/motivooServer/global/healthcheck/DemoController.java
Labels: 🔥PULL REQUEST, ☁️DATABASE, 🪄API, ✨FEAT, 🐈예준🐈

#109 [FEAT] 상대 측의 목표 걸음 수 조회 API 구현
  src/main/java/sopt/org/motivooServer/domain/mission/controller/UserMissionController.java
  src/main/java/sopt/org/motivooServer/domain/mission/dto/response/OpponentGoalStepsResponse.java
  src/main/java/sopt/org/motivooServer/domain/mission/service/UserMissionService.java
  src/main/java/sopt/org/motivooServer/global/response/SuccessType.java
Labels: 🔥PULL REQUEST, 🪄API, ✨FEAT, 🐈예준🐈
